/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../../context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AddToCartInput: { // input type
    menuItemId: string; // String!
    quantity: number; // Int!
    selectedOptions?: string | null; // String
    specialInstructions?: string | null; // String
  }
  AddressInput: { // input type
    city: string; // String!
    country: string; // String!
    isDefault?: boolean | null; // Boolean
    label: string; // String!
    latitude: number; // Float!
    longitude: number; // Float!
    state: string; // String!
    street: string; // String!
    zipCode: string; // String!
  }
  CreateBillingPortalSessionInput: { // input type
    customerId: string; // String!
    returnUrl: string; // String!
  }
  CreateCheckoutSessionInput: { // input type
    cancelUrl: string; // String!
    customerEmail?: string | null; // String
    orderId: string; // String!
    successUrl: string; // String!
  }
  CreateOrderInput: { // input type
    deliveryAddress: string; // String!
    specialInstructions?: string | null; // String
    tip?: number | null; // Float
  }
  CreatePaymentIntentInput: { // input type
    amount: number; // Float!
    currency?: string | null; // String
    description?: string | null; // String
    metadata?: string | null; // String
  }
  CreateRefundInput: { // input type
    amount?: number | null; // Float
    paymentIntentId: string; // String!
    reason?: string | null; // String
  }
  CreateReviewInput: { // input type
    comment?: string | null; // String
    courierId?: string | null; // String
    rating: number; // Int!
    restaurantId?: string | null; // String
    type: NexusGenEnums['ReviewType']; // ReviewType!
  }
  LocationInput: { // input type
    latitude: number; // Float!
    longitude: number; // Float!
  }
  LoginInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  RemoveFromCartInput: { // input type
    cartItemId: string; // String!
  }
  SignupInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    phone?: string | null; // String
  }
  UpdateCartItemInput: { // input type
    cartItemId: string; // String!
    quantity?: number | null; // Int
    selectedOptions?: string | null; // String
    specialInstructions?: string | null; // String
  }
  UpdateCourierLocationInput: { // input type
    latitude: number; // Float!
    longitude: number; // Float!
  }
}

export interface NexusGenEnums {
  DeliveryStatus: "accepted" | "assigned" | "delivered" | "picked_up"
  OptionType: "multiple" | "single"
  OrderStatus: "cancelled" | "confirmed" | "delivered" | "pending" | "picked_up" | "preparing" | "ready"
  PaymentStatus: "failed" | "paid" | "pending" | "refunded"
  ReviewType: "courier" | "restaurant"
  UserRole: "admin" | "courier" | "customer" | "merchant"
  VehicleType: "bike" | "car" | "motorcycle"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Address: { // root type
    city: string; // String!
    country: string; // String!
    createdAt: string; // String!
    id: string; // String!
    isDefault: boolean; // Boolean!
    label: string; // String!
    latitude: number; // Float!
    longitude: number; // Float!
    state: string; // String!
    street: string; // String!
    updatedAt: string; // String!
    userId: string; // String!
    zipCode: string; // String!
  }
  AuthResponse: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  BillingPortalSession: { // root type
    createdAt: string; // String!
    id: string; // String!
    returnUrl: string; // String!
    url: string; // String!
  }
  Cart: { // root type
    createdAt: string; // String!
    id: string; // String!
    restaurantId: string; // String!
    updatedAt: string; // String!
    userId: string; // String!
  }
  CartItem: { // root type
    cartId: string; // String!
    createdAt: string; // String!
    id: string; // String!
    menuItemId: string; // String!
    quantity: number; // Int!
    selectedOptions: string; // String!
    specialInstructions?: string | null; // String
    updatedAt: string; // String!
  }
  CheckoutSession: { // root type
    createdAt: string; // String!
    customerEmail?: string | null; // String
    customerId?: string | null; // String
    expiresAt: string; // String!
    id: string; // String!
    paymentIntentId?: string | null; // String
    status: string; // String!
    url: string; // String!
  }
  CourierLocationUpdate: { // root type
    courierId: string; // String!
    deliveryId: string; // String!
    estimatedArrival?: string | null; // String
    timestamp: string; // String!
  }
  CourierProfile: { // root type
    createdAt: string; // String!
    id: string; // String!
    isAvailable: boolean; // Boolean!
    licensePlate?: string | null; // String
    rating: number; // Float!
    reviewCount: number; // Int!
    totalDeliveries: number; // Int!
    updatedAt: string; // String!
    userId: string; // String!
    vehicleType: NexusGenEnums['VehicleType']; // VehicleType!
  }
  CourierStatusUpdate: { // root type
    courierId: string; // String!
    isAvailable: boolean; // Boolean!
    timestamp: string; // String!
  }
  CourierTrackingUpdate: { // root type
    courierId: string; // String!
    estimatedArrival?: string | null; // String
    timestamp: string; // String!
  }
  Delivery: { // root type
    acceptedAt?: string | null; // String
    assignedAt: string; // String!
    courierId: string; // String!
    createdAt: string; // String!
    deliveredAt?: string | null; // String
    estimatedArrival?: string | null; // String
    id: string; // String!
    orderId: string; // String!
    pickedUpAt?: string | null; // String
    status: NexusGenEnums['DeliveryStatus']; // DeliveryStatus!
    updatedAt: string; // String!
  }
  DeliveryAssignment: { // root type
    assignedBy: string; // String!
    courierId: string; // String!
    deliveryId: string; // String!
    timestamp: string; // String!
  }
  DeliveryStatusUpdate: { // root type
    deliveryId: string; // String!
    message?: string | null; // String
    status: string; // String!
    timestamp: string; // String!
  }
  Location: { // root type
    latitude: number; // Float!
    longitude: number; // Float!
    timestamp?: string | null; // String
  }
  MenuCategory: { // root type
    createdAt: string; // String!
    description?: string | null; // String
    id: string; // String!
    isActive: boolean; // Boolean!
    name: string; // String!
    restaurantId: string; // String!
    sortOrder: number; // Int!
    updatedAt: string; // String!
  }
  MenuItem: { // root type
    categoryId: string; // String!
    createdAt: string; // String!
    description?: string | null; // String
    id: string; // String!
    image?: string | null; // String
    isAvailable: boolean; // Boolean!
    isPopular: boolean; // Boolean!
    name: string; // String!
    price: number; // Float!
    restaurantId: string; // String!
    sortOrder: number; // Int!
    updatedAt: string; // String!
  }
  MenuItemOption: { // root type
    createdAt: string; // String!
    id: string; // String!
    isRequired: boolean; // Boolean!
    menuItemId: string; // String!
    name: string; // String!
    sortOrder: number; // Int!
    type: NexusGenEnums['OptionType']; // OptionType!
  }
  Mutation: {};
  OptionValue: { // root type
    createdAt: string; // String!
    id: string; // String!
    isDefault: boolean; // Boolean!
    name: string; // String!
    optionId: string; // String!
    price: number; // Float!
    sortOrder: number; // Int!
  }
  Order: { // root type
    courierId?: string | null; // String
    createdAt: string; // String!
    customerId: string; // String!
    deliveryAddress: string; // String!
    deliveryFee: number; // Float!
    estimatedDeliveryTime?: string | null; // String
    id: string; // String!
    orderNumber: string; // String!
    paymentStatus: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    restaurantId: string; // String!
    specialInstructions?: string | null; // String
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
    subtotal: number; // Float!
    tax: number; // Float!
    tip: number; // Float!
    total: number; // Float!
    updatedAt: string; // String!
  }
  OrderEvent: { // root type
    createdAt: string; // String!
    id: string; // String!
    message?: string | null; // String
    metadata?: string | null; // String
    orderId: string; // String!
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
  }
  OrderItem: { // root type
    createdAt: string; // String!
    id: string; // String!
    menuItemId: string; // String!
    orderId: string; // String!
    quantity: number; // Int!
    selectedOptions: string; // String!
    specialInstructions?: string | null; // String
    totalPrice: number; // Float!
    unitPrice: number; // Float!
  }
  OrderQueueUpdate: { // root type
    pendingOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    preparingOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    readyOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    restaurantId: string; // String!
    timestamp: string; // String!
  }
  OrderTrackingUpdate: { // root type
    estimatedDelivery?: string | null; // String
    orderId: string; // String!
    status: string; // String!
    timestamp: string; // String!
  }
  OrderUpdate: { // root type
    message?: string | null; // String
    metadata?: string | null; // String
    orderId: string; // String!
    status: string; // String!
    timestamp: string; // String!
  }
  PaymentIntent: { // root type
    amount: number; // Int!
    clientSecret: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    description?: string | null; // String
    id: string; // String!
    metadata?: string | null; // String
    status: string; // String!
  }
  Query: {};
  RefreshTokenResponse: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  Refund: { // root type
    amount: number; // Int!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    reason?: string | null; // String
    status: string; // String!
  }
  Restaurant: { // root type
    createdAt: string; // String!
    cuisine: string; // String!
    deliveryFee: number; // Float!
    deliveryTime: number; // Int!
    description?: string | null; // String
    id: string; // String!
    image?: string | null; // String
    isActive: boolean; // Boolean!
    isFavorite?: boolean | null; // Boolean
    isOpen: boolean; // Boolean!
    minimumOrder: number; // Float!
    name: string; // String!
    phone?: string | null; // String
    rating?: number | null; // Float
    reviewCount: number; // Int!
    slug: string; // String!
    updatedAt: string; // String!
  }
  Review: { // root type
    comment?: string | null; // String
    courierId?: string | null; // String
    createdAt: string; // String!
    customerId: string; // String!
    id: string; // String!
    rating: number; // Int!
    restaurantId?: string | null; // String
    type: NexusGenEnums['ReviewType']; // ReviewType!
    updatedAt: string; // String!
  }
  Subscription: {};
  User: { // root type
    avatar?: string | null; // String
    createdAt: string; // String!
    email: string; // String!
    emailVerified: boolean; // Boolean!
    firstName: string; // String!
    id: string; // String!
    isActive: boolean; // Boolean!
    lastName: string; // String!
    phone?: string | null; // String
    role: NexusGenEnums['UserRole']; // UserRole!
    updatedAt: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Address: { // field return type
    city: string; // String!
    country: string; // String!
    createdAt: string; // String!
    id: string; // String!
    isDefault: boolean; // Boolean!
    label: string; // String!
    latitude: number; // Float!
    longitude: number; // Float!
    state: string; // String!
    street: string; // String!
    updatedAt: string; // String!
    userId: string; // String!
    zipCode: string; // String!
  }
  AuthResponse: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  BillingPortalSession: { // field return type
    createdAt: string; // String!
    id: string; // String!
    returnUrl: string; // String!
    url: string; // String!
  }
  Cart: { // field return type
    createdAt: string; // String!
    id: string; // String!
    items: Array<NexusGenRootTypes['CartItem'] | null> | null; // [CartItem]
    restaurant: NexusGenRootTypes['Restaurant'] | null; // Restaurant
    restaurantId: string; // String!
    updatedAt: string; // String!
    userId: string; // String!
  }
  CartItem: { // field return type
    cartId: string; // String!
    createdAt: string; // String!
    id: string; // String!
    menuItem: NexusGenRootTypes['MenuItem'] | null; // MenuItem
    menuItemId: string; // String!
    quantity: number; // Int!
    selectedOptions: string; // String!
    specialInstructions: string | null; // String
    updatedAt: string; // String!
  }
  CheckoutSession: { // field return type
    createdAt: string; // String!
    customerEmail: string | null; // String
    customerId: string | null; // String
    expiresAt: string; // String!
    id: string; // String!
    paymentIntentId: string | null; // String
    status: string; // String!
    url: string; // String!
  }
  CourierLocationUpdate: { // field return type
    courierId: string; // String!
    deliveryId: string; // String!
    estimatedArrival: string | null; // String
    location: NexusGenRootTypes['Location'] | null; // Location
    timestamp: string; // String!
  }
  CourierProfile: { // field return type
    createdAt: string; // String!
    currentLocation: NexusGenRootTypes['Location'] | null; // Location
    id: string; // String!
    isAvailable: boolean; // Boolean!
    licensePlate: string | null; // String
    rating: number; // Float!
    reviewCount: number; // Int!
    totalDeliveries: number; // Int!
    updatedAt: string; // String!
    user: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
    vehicleType: NexusGenEnums['VehicleType']; // VehicleType!
  }
  CourierStatusUpdate: { // field return type
    courierId: string; // String!
    isAvailable: boolean; // Boolean!
    timestamp: string; // String!
  }
  CourierTrackingUpdate: { // field return type
    courierId: string; // String!
    currentLocation: NexusGenRootTypes['Location'] | null; // Location
    estimatedArrival: string | null; // String
    timestamp: string; // String!
  }
  Delivery: { // field return type
    acceptedAt: string | null; // String
    assignedAt: string; // String!
    courier: NexusGenRootTypes['User'] | null; // User
    courierId: string; // String!
    createdAt: string; // String!
    currentLocation: NexusGenRootTypes['Location'] | null; // Location
    deliveredAt: string | null; // String
    estimatedArrival: string | null; // String
    id: string; // String!
    order: NexusGenRootTypes['Order'] | null; // Order
    orderId: string; // String!
    pickedUpAt: string | null; // String
    status: NexusGenEnums['DeliveryStatus']; // DeliveryStatus!
    updatedAt: string; // String!
  }
  DeliveryAssignment: { // field return type
    assignedBy: string; // String!
    courierId: string; // String!
    deliveryId: string; // String!
    timestamp: string; // String!
  }
  DeliveryStatusUpdate: { // field return type
    deliveryId: string; // String!
    message: string | null; // String
    status: string; // String!
    timestamp: string; // String!
  }
  Location: { // field return type
    latitude: number; // Float!
    longitude: number; // Float!
    timestamp: string | null; // String
  }
  MenuCategory: { // field return type
    createdAt: string; // String!
    description: string | null; // String
    id: string; // String!
    isActive: boolean; // Boolean!
    menuItems: Array<NexusGenRootTypes['MenuItem'] | null> | null; // [MenuItem]
    name: string; // String!
    restaurantId: string; // String!
    sortOrder: number; // Int!
    updatedAt: string; // String!
  }
  MenuItem: { // field return type
    categoryId: string; // String!
    createdAt: string; // String!
    description: string | null; // String
    id: string; // String!
    image: string | null; // String
    isAvailable: boolean; // Boolean!
    isPopular: boolean; // Boolean!
    name: string; // String!
    options: Array<NexusGenRootTypes['MenuItemOption'] | null> | null; // [MenuItemOption]
    price: number; // Float!
    restaurantId: string; // String!
    sortOrder: number; // Int!
    updatedAt: string; // String!
  }
  MenuItemOption: { // field return type
    createdAt: string; // String!
    id: string; // String!
    isRequired: boolean; // Boolean!
    menuItemId: string; // String!
    name: string; // String!
    sortOrder: number; // Int!
    type: NexusGenEnums['OptionType']; // OptionType!
    values: Array<NexusGenRootTypes['OptionValue'] | null> | null; // [OptionValue]
  }
  Mutation: { // field return type
    acceptDelivery: NexusGenRootTypes['Delivery'] | null; // Delivery
    addToCart: NexusGenRootTypes['CartItem'] | null; // CartItem
    cancelPaymentIntent: NexusGenRootTypes['PaymentIntent'] | null; // PaymentIntent
    clearCart: boolean | null; // Boolean
    confirmOrder: NexusGenRootTypes['Order'] | null; // Order
    confirmPaymentIntent: NexusGenRootTypes['PaymentIntent'] | null; // PaymentIntent
    createBillingPortalSession: NexusGenRootTypes['BillingPortalSession'] | null; // BillingPortalSession
    createCheckoutSession: NexusGenRootTypes['CheckoutSession'] | null; // CheckoutSession
    createPaymentIntent: NexusGenRootTypes['PaymentIntent'] | null; // PaymentIntent
    createRefund: NexusGenRootTypes['Refund'] | null; // Refund
    createReview: NexusGenRootTypes['Review'] | null; // Review
    deliverOrder: NexusGenRootTypes['Delivery'] | null; // Delivery
    login: NexusGenRootTypes['AuthResponse'] | null; // AuthResponse
    loginWithGoogle: NexusGenRootTypes['AuthResponse'] | null; // AuthResponse
    logout: boolean | null; // Boolean
    pickupOrder: NexusGenRootTypes['Delivery'] | null; // Delivery
    placeOrder: NexusGenRootTypes['Order'] | null; // Order
    refreshToken: NexusGenRootTypes['RefreshTokenResponse'] | null; // RefreshTokenResponse
    removeFromCart: boolean | null; // Boolean
    setRestaurantOpen: NexusGenRootTypes['Restaurant'] | null; // Restaurant
    signup: NexusGenRootTypes['AuthResponse'] | null; // AuthResponse
    toggleFavorite: boolean | null; // Boolean
    updateCartItem: NexusGenRootTypes['CartItem'] | null; // CartItem
    updateCourierLocation: NexusGenRootTypes['CourierProfile'] | null; // CourierProfile
  }
  OptionValue: { // field return type
    createdAt: string; // String!
    id: string; // String!
    isDefault: boolean; // Boolean!
    name: string; // String!
    optionId: string; // String!
    price: number; // Float!
    sortOrder: number; // Int!
  }
  Order: { // field return type
    courier: NexusGenRootTypes['User'] | null; // User
    courierId: string | null; // String
    createdAt: string; // String!
    customer: NexusGenRootTypes['User'] | null; // User
    customerId: string; // String!
    deliveryAddress: string; // String!
    deliveryFee: number; // Float!
    estimatedDeliveryTime: string | null; // String
    events: Array<NexusGenRootTypes['OrderEvent'] | null> | null; // [OrderEvent]
    id: string; // String!
    items: Array<NexusGenRootTypes['OrderItem'] | null> | null; // [OrderItem]
    orderNumber: string; // String!
    paymentStatus: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    restaurant: NexusGenRootTypes['Restaurant'] | null; // Restaurant
    restaurantId: string; // String!
    specialInstructions: string | null; // String
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
    subtotal: number; // Float!
    tax: number; // Float!
    tip: number; // Float!
    total: number; // Float!
    updatedAt: string; // String!
  }
  OrderEvent: { // field return type
    createdAt: string; // String!
    id: string; // String!
    message: string | null; // String
    metadata: string | null; // String
    orderId: string; // String!
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
  }
  OrderItem: { // field return type
    createdAt: string; // String!
    id: string; // String!
    menuItem: NexusGenRootTypes['MenuItem'] | null; // MenuItem
    menuItemId: string; // String!
    orderId: string; // String!
    quantity: number; // Int!
    selectedOptions: string; // String!
    specialInstructions: string | null; // String
    totalPrice: number; // Float!
    unitPrice: number; // Float!
  }
  OrderQueueUpdate: { // field return type
    pendingOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    preparingOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    readyOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    restaurantId: string; // String!
    timestamp: string; // String!
  }
  OrderTrackingUpdate: { // field return type
    courier: NexusGenRootTypes['User'] | null; // User
    currentLocation: NexusGenRootTypes['Location'] | null; // Location
    estimatedDelivery: string | null; // String
    orderId: string; // String!
    status: string; // String!
    timestamp: string; // String!
  }
  OrderUpdate: { // field return type
    message: string | null; // String
    metadata: string | null; // String
    orderId: string; // String!
    status: string; // String!
    timestamp: string; // String!
  }
  PaymentIntent: { // field return type
    amount: number; // Int!
    clientSecret: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    description: string | null; // String
    id: string; // String!
    metadata: string | null; // String
    status: string; // String!
  }
  Query: { // field return type
    cart: NexusGenRootTypes['Cart'] | null; // Cart
    courierAssignments: Array<NexusGenRootTypes['Delivery'] | null>; // [Delivery]!
    favoriteRestaurants: Array<NexusGenRootTypes['Restaurant'] | null>; // [Restaurant]!
    me: NexusGenRootTypes['User'] | null; // User
    merchantOrders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    order: NexusGenRootTypes['Order'] | null; // Order
    orders: Array<NexusGenRootTypes['Order'] | null>; // [Order]!
    paymentIntent: NexusGenRootTypes['PaymentIntent'] | null; // PaymentIntent
    restaurant: NexusGenRootTypes['Restaurant'] | null; // Restaurant
    restaurants: Array<NexusGenRootTypes['Restaurant'] | null>; // [Restaurant]!
    reviews: Array<NexusGenRootTypes['Review'] | null>; // [Review]!
  }
  RefreshTokenResponse: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  Refund: { // field return type
    amount: number; // Int!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    reason: string | null; // String
    status: string; // String!
  }
  Restaurant: { // field return type
    address: NexusGenRootTypes['Address'] | null; // Address
    createdAt: string; // String!
    cuisine: string; // String!
    deliveryFee: number; // Float!
    deliveryTime: number; // Int!
    description: string | null; // String
    id: string; // String!
    image: string | null; // String
    isActive: boolean; // Boolean!
    isFavorite: boolean | null; // Boolean
    isOpen: boolean; // Boolean!
    menuCategories: Array<NexusGenRootTypes['MenuCategory'] | null> | null; // [MenuCategory]
    minimumOrder: number; // Float!
    name: string; // String!
    phone: string | null; // String
    rating: number | null; // Float
    reviewCount: number; // Int!
    slug: string; // String!
    updatedAt: string; // String!
  }
  Review: { // field return type
    comment: string | null; // String
    courier: NexusGenRootTypes['User'] | null; // User
    courierId: string | null; // String
    createdAt: string; // String!
    customer: NexusGenRootTypes['User'] | null; // User
    customerId: string; // String!
    id: string; // String!
    rating: number; // Int!
    restaurant: NexusGenRootTypes['Restaurant'] | null; // Restaurant
    restaurantId: string | null; // String
    type: NexusGenEnums['ReviewType']; // ReviewType!
    updatedAt: string; // String!
  }
  Subscription: { // field return type
    courierLocation: NexusGenRootTypes['CourierLocationUpdate'] | null; // CourierLocationUpdate
    courierStatusChanged: NexusGenRootTypes['CourierStatusUpdate'] | null; // CourierStatusUpdate
    customerOrderTracking: NexusGenRootTypes['OrderTrackingUpdate'] | null; // OrderTrackingUpdate
    deliveryAssigned: NexusGenRootTypes['DeliveryAssignment'] | null; // DeliveryAssignment
    deliveryStatusChanged: NexusGenRootTypes['DeliveryStatusUpdate'] | null; // DeliveryStatusUpdate
    liveCourierTracking: NexusGenRootTypes['CourierTrackingUpdate'] | null; // CourierTrackingUpdate
    merchantIncomingOrders: NexusGenRootTypes['Order'] | null; // Order
    orderStatusChanged: NexusGenRootTypes['OrderEvent'] | null; // OrderEvent
    realTimeOrderUpdates: NexusGenRootTypes['OrderUpdate'] | null; // OrderUpdate
    restaurantOrderQueue: NexusGenRootTypes['OrderQueueUpdate'] | null; // OrderQueueUpdate
  }
  User: { // field return type
    addresses: Array<NexusGenRootTypes['Address'] | null> | null; // [Address]
    avatar: string | null; // String
    courierProfile: NexusGenRootTypes['CourierProfile'] | null; // CourierProfile
    createdAt: string; // String!
    email: string; // String!
    emailVerified: boolean; // Boolean!
    firstName: string; // String!
    id: string; // String!
    isActive: boolean; // Boolean!
    lastName: string; // String!
    phone: string | null; // String
    role: NexusGenEnums['UserRole']; // UserRole!
    updatedAt: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Address: { // field return type name
    city: 'String'
    country: 'String'
    createdAt: 'String'
    id: 'String'
    isDefault: 'Boolean'
    label: 'String'
    latitude: 'Float'
    longitude: 'Float'
    state: 'String'
    street: 'String'
    updatedAt: 'String'
    userId: 'String'
    zipCode: 'String'
  }
  AuthResponse: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
    user: 'User'
  }
  BillingPortalSession: { // field return type name
    createdAt: 'String'
    id: 'String'
    returnUrl: 'String'
    url: 'String'
  }
  Cart: { // field return type name
    createdAt: 'String'
    id: 'String'
    items: 'CartItem'
    restaurant: 'Restaurant'
    restaurantId: 'String'
    updatedAt: 'String'
    userId: 'String'
  }
  CartItem: { // field return type name
    cartId: 'String'
    createdAt: 'String'
    id: 'String'
    menuItem: 'MenuItem'
    menuItemId: 'String'
    quantity: 'Int'
    selectedOptions: 'String'
    specialInstructions: 'String'
    updatedAt: 'String'
  }
  CheckoutSession: { // field return type name
    createdAt: 'String'
    customerEmail: 'String'
    customerId: 'String'
    expiresAt: 'String'
    id: 'String'
    paymentIntentId: 'String'
    status: 'String'
    url: 'String'
  }
  CourierLocationUpdate: { // field return type name
    courierId: 'String'
    deliveryId: 'String'
    estimatedArrival: 'String'
    location: 'Location'
    timestamp: 'String'
  }
  CourierProfile: { // field return type name
    createdAt: 'String'
    currentLocation: 'Location'
    id: 'String'
    isAvailable: 'Boolean'
    licensePlate: 'String'
    rating: 'Float'
    reviewCount: 'Int'
    totalDeliveries: 'Int'
    updatedAt: 'String'
    user: 'User'
    userId: 'String'
    vehicleType: 'VehicleType'
  }
  CourierStatusUpdate: { // field return type name
    courierId: 'String'
    isAvailable: 'Boolean'
    timestamp: 'String'
  }
  CourierTrackingUpdate: { // field return type name
    courierId: 'String'
    currentLocation: 'Location'
    estimatedArrival: 'String'
    timestamp: 'String'
  }
  Delivery: { // field return type name
    acceptedAt: 'String'
    assignedAt: 'String'
    courier: 'User'
    courierId: 'String'
    createdAt: 'String'
    currentLocation: 'Location'
    deliveredAt: 'String'
    estimatedArrival: 'String'
    id: 'String'
    order: 'Order'
    orderId: 'String'
    pickedUpAt: 'String'
    status: 'DeliveryStatus'
    updatedAt: 'String'
  }
  DeliveryAssignment: { // field return type name
    assignedBy: 'String'
    courierId: 'String'
    deliveryId: 'String'
    timestamp: 'String'
  }
  DeliveryStatusUpdate: { // field return type name
    deliveryId: 'String'
    message: 'String'
    status: 'String'
    timestamp: 'String'
  }
  Location: { // field return type name
    latitude: 'Float'
    longitude: 'Float'
    timestamp: 'String'
  }
  MenuCategory: { // field return type name
    createdAt: 'String'
    description: 'String'
    id: 'String'
    isActive: 'Boolean'
    menuItems: 'MenuItem'
    name: 'String'
    restaurantId: 'String'
    sortOrder: 'Int'
    updatedAt: 'String'
  }
  MenuItem: { // field return type name
    categoryId: 'String'
    createdAt: 'String'
    description: 'String'
    id: 'String'
    image: 'String'
    isAvailable: 'Boolean'
    isPopular: 'Boolean'
    name: 'String'
    options: 'MenuItemOption'
    price: 'Float'
    restaurantId: 'String'
    sortOrder: 'Int'
    updatedAt: 'String'
  }
  MenuItemOption: { // field return type name
    createdAt: 'String'
    id: 'String'
    isRequired: 'Boolean'
    menuItemId: 'String'
    name: 'String'
    sortOrder: 'Int'
    type: 'OptionType'
    values: 'OptionValue'
  }
  Mutation: { // field return type name
    acceptDelivery: 'Delivery'
    addToCart: 'CartItem'
    cancelPaymentIntent: 'PaymentIntent'
    clearCart: 'Boolean'
    confirmOrder: 'Order'
    confirmPaymentIntent: 'PaymentIntent'
    createBillingPortalSession: 'BillingPortalSession'
    createCheckoutSession: 'CheckoutSession'
    createPaymentIntent: 'PaymentIntent'
    createRefund: 'Refund'
    createReview: 'Review'
    deliverOrder: 'Delivery'
    login: 'AuthResponse'
    loginWithGoogle: 'AuthResponse'
    logout: 'Boolean'
    pickupOrder: 'Delivery'
    placeOrder: 'Order'
    refreshToken: 'RefreshTokenResponse'
    removeFromCart: 'Boolean'
    setRestaurantOpen: 'Restaurant'
    signup: 'AuthResponse'
    toggleFavorite: 'Boolean'
    updateCartItem: 'CartItem'
    updateCourierLocation: 'CourierProfile'
  }
  OptionValue: { // field return type name
    createdAt: 'String'
    id: 'String'
    isDefault: 'Boolean'
    name: 'String'
    optionId: 'String'
    price: 'Float'
    sortOrder: 'Int'
  }
  Order: { // field return type name
    courier: 'User'
    courierId: 'String'
    createdAt: 'String'
    customer: 'User'
    customerId: 'String'
    deliveryAddress: 'String'
    deliveryFee: 'Float'
    estimatedDeliveryTime: 'String'
    events: 'OrderEvent'
    id: 'String'
    items: 'OrderItem'
    orderNumber: 'String'
    paymentStatus: 'PaymentStatus'
    restaurant: 'Restaurant'
    restaurantId: 'String'
    specialInstructions: 'String'
    status: 'OrderStatus'
    subtotal: 'Float'
    tax: 'Float'
    tip: 'Float'
    total: 'Float'
    updatedAt: 'String'
  }
  OrderEvent: { // field return type name
    createdAt: 'String'
    id: 'String'
    message: 'String'
    metadata: 'String'
    orderId: 'String'
    status: 'OrderStatus'
  }
  OrderItem: { // field return type name
    createdAt: 'String'
    id: 'String'
    menuItem: 'MenuItem'
    menuItemId: 'String'
    orderId: 'String'
    quantity: 'Int'
    selectedOptions: 'String'
    specialInstructions: 'String'
    totalPrice: 'Float'
    unitPrice: 'Float'
  }
  OrderQueueUpdate: { // field return type name
    pendingOrders: 'Order'
    preparingOrders: 'Order'
    readyOrders: 'Order'
    restaurantId: 'String'
    timestamp: 'String'
  }
  OrderTrackingUpdate: { // field return type name
    courier: 'User'
    currentLocation: 'Location'
    estimatedDelivery: 'String'
    orderId: 'String'
    status: 'String'
    timestamp: 'String'
  }
  OrderUpdate: { // field return type name
    message: 'String'
    metadata: 'String'
    orderId: 'String'
    status: 'String'
    timestamp: 'String'
  }
  PaymentIntent: { // field return type name
    amount: 'Int'
    clientSecret: 'String'
    createdAt: 'String'
    currency: 'String'
    description: 'String'
    id: 'String'
    metadata: 'String'
    status: 'String'
  }
  Query: { // field return type name
    cart: 'Cart'
    courierAssignments: 'Delivery'
    favoriteRestaurants: 'Restaurant'
    me: 'User'
    merchantOrders: 'Order'
    order: 'Order'
    orders: 'Order'
    paymentIntent: 'PaymentIntent'
    restaurant: 'Restaurant'
    restaurants: 'Restaurant'
    reviews: 'Review'
  }
  RefreshTokenResponse: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
  }
  Refund: { // field return type name
    amount: 'Int'
    createdAt: 'String'
    currency: 'String'
    id: 'String'
    reason: 'String'
    status: 'String'
  }
  Restaurant: { // field return type name
    address: 'Address'
    createdAt: 'String'
    cuisine: 'String'
    deliveryFee: 'Float'
    deliveryTime: 'Int'
    description: 'String'
    id: 'String'
    image: 'String'
    isActive: 'Boolean'
    isFavorite: 'Boolean'
    isOpen: 'Boolean'
    menuCategories: 'MenuCategory'
    minimumOrder: 'Float'
    name: 'String'
    phone: 'String'
    rating: 'Float'
    reviewCount: 'Int'
    slug: 'String'
    updatedAt: 'String'
  }
  Review: { // field return type name
    comment: 'String'
    courier: 'User'
    courierId: 'String'
    createdAt: 'String'
    customer: 'User'
    customerId: 'String'
    id: 'String'
    rating: 'Int'
    restaurant: 'Restaurant'
    restaurantId: 'String'
    type: 'ReviewType'
    updatedAt: 'String'
  }
  Subscription: { // field return type name
    courierLocation: 'CourierLocationUpdate'
    courierStatusChanged: 'CourierStatusUpdate'
    customerOrderTracking: 'OrderTrackingUpdate'
    deliveryAssigned: 'DeliveryAssignment'
    deliveryStatusChanged: 'DeliveryStatusUpdate'
    liveCourierTracking: 'CourierTrackingUpdate'
    merchantIncomingOrders: 'Order'
    orderStatusChanged: 'OrderEvent'
    realTimeOrderUpdates: 'OrderUpdate'
    restaurantOrderQueue: 'OrderQueueUpdate'
  }
  User: { // field return type name
    addresses: 'Address'
    avatar: 'String'
    courierProfile: 'CourierProfile'
    createdAt: 'String'
    email: 'String'
    emailVerified: 'Boolean'
    firstName: 'String'
    id: 'String'
    isActive: 'Boolean'
    lastName: 'String'
    phone: 'String'
    role: 'UserRole'
    updatedAt: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    acceptDelivery: { // args
      deliveryId: string; // String!
    }
    addToCart: { // args
      input: NexusGenInputs['AddToCartInput']; // AddToCartInput!
    }
    cancelPaymentIntent: { // args
      paymentIntentId: string; // String!
    }
    confirmOrder: { // args
      orderId: string; // String!
    }
    confirmPaymentIntent: { // args
      paymentIntentId: string; // String!
    }
    createBillingPortalSession: { // args
      input: NexusGenInputs['CreateBillingPortalSessionInput']; // CreateBillingPortalSessionInput!
    }
    createCheckoutSession: { // args
      input: NexusGenInputs['CreateCheckoutSessionInput']; // CreateCheckoutSessionInput!
    }
    createPaymentIntent: { // args
      input: NexusGenInputs['CreatePaymentIntentInput']; // CreatePaymentIntentInput!
    }
    createRefund: { // args
      input: NexusGenInputs['CreateRefundInput']; // CreateRefundInput!
    }
    createReview: { // args
      input: NexusGenInputs['CreateReviewInput']; // CreateReviewInput!
    }
    deliverOrder: { // args
      deliveryId: string; // String!
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    loginWithGoogle: { // args
      idToken: string; // String!
    }
    pickupOrder: { // args
      deliveryId: string; // String!
    }
    placeOrder: { // args
      input: NexusGenInputs['CreateOrderInput']; // CreateOrderInput!
    }
    refreshToken: { // args
      refreshToken: string; // String!
    }
    removeFromCart: { // args
      input: NexusGenInputs['RemoveFromCartInput']; // RemoveFromCartInput!
    }
    setRestaurantOpen: { // args
      id: string; // String!
      isOpen: boolean; // Boolean!
    }
    signup: { // args
      input: NexusGenInputs['SignupInput']; // SignupInput!
    }
    toggleFavorite: { // args
      restaurantId: string; // String!
    }
    updateCartItem: { // args
      input: NexusGenInputs['UpdateCartItemInput']; // UpdateCartItemInput!
    }
    updateCourierLocation: { // args
      input: NexusGenInputs['UpdateCourierLocationInput']; // UpdateCourierLocationInput!
    }
  }
  Query: {
    merchantOrders: { // args
      limit?: number | null; // Int
      offset?: number | null; // Int
      status?: NexusGenEnums['OrderStatus'] | null; // OrderStatus
    }
    order: { // args
      id: string; // String!
    }
    orders: { // args
      limit?: number | null; // Int
      offset?: number | null; // Int
      status?: NexusGenEnums['OrderStatus'] | null; // OrderStatus
    }
    paymentIntent: { // args
      paymentIntentId: string; // String!
    }
    restaurant: { // args
      slug: string; // String!
    }
    restaurants: { // args
      cuisine?: string | null; // String
      isOpen?: boolean | null; // Boolean
      limit?: number | null; // Int
      offset?: number | null; // Int
      search?: string | null; // String
      sortBy?: string | null; // String
      sortOrder?: string | null; // String
    }
    reviews: { // args
      courierId?: string | null; // String
      limit?: number | null; // Int
      offset?: number | null; // Int
      restaurantId?: string | null; // String
    }
  }
  Subscription: {
    courierLocation: { // args
      deliveryId: string; // String!
    }
    customerOrderTracking: { // args
      orderId: string; // String!
    }
    deliveryAssigned: { // args
      courierId: string; // String!
    }
    deliveryStatusChanged: { // args
      deliveryId: string; // String!
    }
    liveCourierTracking: { // args
      courierId: string; // String!
    }
    merchantIncomingOrders: { // args
      restaurantId: string; // String!
    }
    orderStatusChanged: { // args
      orderId: string; // String!
    }
    realTimeOrderUpdates: { // args
      orderId: string; // String!
    }
    restaurantOrderQueue: { // args
      restaurantId: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: true
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}